package solver

func DefaultArchetypes() []Archetype {
	return []Archetype{
		{
			Name: "computeToData",
			Attributes: map[string]any{
				"family":                      "computeToData",
				"parties_exposed":             1.0,
				"transfer_hops":               3.0,
				"processing_percent_base":     0.304787,
				"processing_percent_slope":    0.0000056890,
				"startup_ms":                  1700.0,
				"processing_base_ms":          671.333,
				"processing_slope_ms_per_row": 0.064,
				"transfer_base_ms":            216.667,
				"transfer_slope_ms_per_row":   0.0354,
				"cost_per_provider_eur":       0.50,
			},
		},
		{
			Name: "dataThroughTtp",
			Attributes: map[string]any{
				"family":                      "dataThroughTtp",
				"parties_exposed":             3.0,
				"transfer_hops":               6.0,
				"processing_percent_base":     0.259093,
				"processing_percent_slope":    0.0000011440,
				"startup_ms":                  1660.0,
				"processing_base_ms":          582.200,
				"processing_slope_ms_per_row": 0.0577,
				"transfer_base_ms":            203.333,
				"transfer_slope_ms_per_row":   0.1237,
				"cost_per_request_eur":        0.70,
			},
		},
		{
			Name: "computeToData-cached",
			Attributes: map[string]any{
				"family":                      "computeToData",
				"is_cached":                   true, 
				"parties_exposed":             1.0,  
				"transfer_hops":               0.3,  
				"processing_percent_base":     0.02,
				"processing_percent_slope":    1.0e-8,
				"startup_ms":                  120.0,
				"processing_base_ms":          25.0,
				"processing_slope_ms_per_row": 0.001,
				"transfer_base_ms":            40.0,
				"transfer_slope_ms_per_row":   0.0015,
				"cost_per_provider_eur":       0.50,
			},
		},
		{
			Name: "dataThroughTtp-cached",
			Attributes: map[string]any{
				"family":                      "dataThroughTtp",
				"is_cached":                   true, 
				"parties_exposed":             3.0,  
				"transfer_hops":               0.4,  
				"processing_percent_base":     0.02,
				"processing_percent_slope":    1.0e-8,
				"startup_ms":                  120.0,
				"processing_base_ms":          25.0,
				"processing_slope_ms_per_row": 0.001,
				"transfer_base_ms":            45.0,
				"transfer_slope_ms_per_row":   0.005,
				"cost_per_request_eur":        0.70, 
			},
		},

		{
			Name: "computeToData-compressed",
			Attributes: map[string]any{
				"family":                      "computeToData",
				"parties_exposed":             1.0,
				"transfer_hops":               2.6, 
				"processing_percent_base":     0.314, 
				"processing_percent_slope":    0.0000058600,
				"startup_ms":                  1700.0,
				"processing_base_ms":          685.0, 
				"processing_slope_ms_per_row": 0.0658,
				"transfer_base_ms":            216.667,
				"transfer_slope_ms_per_row":   0.0290,
				"cost_per_provider_eur":       0.50,
			},
		},
		{
			Name: "dataThroughTtp-compressed",
			Attributes: map[string]any{
				"family":                      "dataThroughTtp",
				"parties_exposed":             3.0,
				"transfer_hops":               6.0, 
				"processing_percent_base":     0.262, 
				"processing_percent_slope":    0.0000011600,
				"startup_ms":                  1660.0,
				"processing_base_ms":          590.0,
				"processing_slope_ms_per_row": 0.0584,
				"transfer_base_ms":            203.333,
				"transfer_slope_ms_per_row":   0.1180,
				"cost_per_request_eur":        0.70,
			},
		},
	}
}
